# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
       - image: circleci/ruby:2.4.1-node-browsers

    working_directory: ~/repo
    no_output_timeout: 2m

    steps:
      # Download and cache Pod dependencies
      - restore_cache:
          keys:
          - v1-commit-dependencies-

      - run:
          name: run scan
          command: |

            lastCommit () {
                curl https://api.github.com/repos/CocoaPods/Specs/git/refs/heads/master?access_token=${GITHUB_TOKEN} | grep '"sha"' | cut -d'"' -f 4
            }

            updates () {
                curl https://api.github.com/repos/CocoaPods/Specs/compare/$(cat lastScannedCommit)...$1?access_token=${GITHUB_TOKEN} \
                | grep filename \
                | cut -d'"' -f 4 \
                | xargs dirname \
                | rev | cut -d'/' -f -2 | rev \
                | sort
            }
            
            ls -la # Does updates exist?
            echo "========"
            
            export previousCommit=$(lastCommit)

            # Only post if updates found and not too much
            [ updates $previousCommit > updates ] && [ $(stat --printf="%s" updates) -le 5000 ] && export METHOD=POST || export METHOD=GET
            
            [ -z "$ANALYSER_URL" ] && curl -d "@updates" -X $METHOD ${ANALYSER_URL}

            echo $previousCommit > ./lastScannedCommit

      - save_cache:
          paths:
            - ./lastScannedCommit
          key: v1-commit-dependencies-

      - store_artifacts:
          path: lastScannedCommit
      - store_artifacts:
          path: updates


workflows:
  version: 2
  commit:
    jobs:
      - build
  heartbits:
    triggers:
      - schedule:
          cron: "1 5 * 1,2,3,4,5 *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build
