# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
       - image: circleci/ruby:2.4.1-node-browsers
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache Gem dependencies
      - restore_cache:
          keys:
          - v1-gem-dependencies-{{ checksum "Gemfile" }}
          # fallback to using the latest cache if no exact match is found
          - v1-gem-dependencies-

      - run:
          name: install Gem dependencies
          command: |
            bundle install --jobs=4 --retry=3 --path vendor/bundle

      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-gem-dependencies-{{ checksum "Gemfile" }}

      # Download and cache Pod dependencies
      - restore_cache:
          keys:
          - v1-pod-dependencies-{{ checksum "Podfile" }}
          # fallback to using the latest cache if no exact match is found
          - v1-pod-dependencies-

      - run:
          name: install Pod dependencies
          command: |
            export CP_REPOS_DIR=./pods
            bundle exec pod install

      - save_cache:
          paths:
            - ./pods
          key: v1-pod-dependencies-{{ checksum "Podfile" }}

      - run:
          name: run scan
          command: |
            ls -la
            ls -la pods

#      - store_artifacts:
#          path: /tmp/test-results
#          destination: test-results

workflows:
  version: 2
  commit:
    jobs:
      - build
  heartbits:
    triggers:
      - schedule:
          cron: "1 * * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build
