# Check https://circleci.com/docs/2.0/language-ruby/ for more details
version: 2
jobs:
  build:
    docker:
       - image: circleci/ruby:2.4.1-node-browsers
    environment:
       - SPECS_REPO: https://api.github.com/repos/CocoaPods/Specs

    working_directory: ~/repo
    no_output_timeout: 2m

    steps:
      # Download and cache Pod dependencies
      - restore_cache:
          keys:
          - v1-commit-dependencies-

      - run:
          name: run scan
          command: |

            ls -la # DBG - Does updates exist?
            echo "========"

            export MASTER_HEAD=$(curl ${SPECS_REPO}/git/refs/heads/master?access_token=${GITHUB_TOKEN} \
                                 | grep '"sha"' \
                                 | cut -d'"' -f 4)

            compareTo () {
                echo Comparing $(cat lastScannedCommit)...$1 
                curl ${SPECS_REPO}/compare/$(cat lastScannedCommit)...$1?access_token=${GITHUB_TOKEN} \
                | grep filename \
                | cut -d'"' -f 4 \
                | xargs dirname \
                | rev | cut -d'/' -f -2 | rev \
                | sort
            }

            listUpdatesTo () {
                compareTo $1 > updates
            }

            isNotTooMuch () {
                [ $(stat --printf="%s" updates) -le 50000 ]
            }

            if listUpdatesTo $MASTER_HEAD && isNotTooMuch; then
                export METHOD=POST
            else
                export METHOD=GET
            fi
            
            echo $METHOD

            curl -d "@updates" -X $METHOD ${ANALYSER_URL}

            echo $MASTER_HEAD > ./lastScannedCommit

      - save_cache:
          paths:
            - ./lastScannedCommit
          key: v1-commit-dependencies-

      - store_artifacts:
          path: lastScannedCommit
      - store_artifacts:
          path: updates


workflows:
  version: 2
  commit:
    jobs:
      - build
  heartbits:
    triggers:
      - schedule:
          cron: "1 5 * 1,2,3,4,5 *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build
