# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
       - image: circleci/ruby:2.4.1-node-browsers

    working_directory: ~/repo
    no_output_timeout: 2m

    steps:
      # Download and cache Pod dependencies
      - restore_cache:
          keys:
          - v1-commit-dependencies-

      - run:
          name: run scan
          command: |
            export lastCommit=$(curl https://api.github.com/repos/CocoaPods/Specs/git/refs/heads/master)

            curl https://api.github.com/repos/CocoaPods/Specs/compare/$(cat lastScannedCommit)...$lastCommit  2>/dev/null \
            | grep filename \
            | sed 's/.podspec.json//g' \
            | cut -d'"' -f 4 \
            | rev | cut -d'/' -f -1 -f 2 | rev \
            | sed 's,\(.*\)\(/\)\(.*\),\3\2\1,g' \
            | sort |
            > updates
            
            if [ -z "$ANALYSER_URL" ]
            then
                export METHOD=$([ $(stat --printf="%s" updates) -ge 5000 ] && echo GET || echo POST) # Use GET for large files
                curl -d "@updates" -X $METHOD ${ANALYSER_URL}
            fi

            echo $lastCommit > ./lastScannedCommit

      - save_cache:
          paths:
            - ./lastScannedCommit
          key: v1-commit-dependencies-

      - store_artifacts:
          path: lastScannedCommit
      - store_artifacts:
          path: updates


workflows:
  version: 2
  commit:
    jobs:
      - build
  heartbits:
    triggers:
      - schedule:
          cron: "1 5 * 1,2,3,4,5 *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build
